apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tqo63u3ns-python
  janus-idp.io/tekton: tqo63u3ns-python
  backstage.io/kubernetes-id: tqo63u3ns-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tqo63u3ns-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
